services:
  - type: web
    name: sabr-test
    runtime: docker
    plan: free
    region: oregon
    branch: tushar
    dockerfilePath: ./Dockerfile.sabr_warp
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: WARP_PROXY
        value: socks5://127.0.0.1:40000
